// protoc --go_out=./pkg --go_opt=paths=source_relative --go-grpc_out=./pkg --go-grpc_opt=paths=source_relative ./api/chatpb/chat.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: api/unit/unit.proto

package unit_v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UnitsParamsResponce_Status int32

const (
	UnitsParamsResponce_OK      UnitsParamsResponce_Status = 0
	UnitsParamsResponce_ERROR   UnitsParamsResponce_Status = 1
	UnitsParamsResponce_UNKNOWN UnitsParamsResponce_Status = 2
)

// Enum value maps for UnitsParamsResponce_Status.
var (
	UnitsParamsResponce_Status_name = map[int32]string{
		0: "OK",
		1: "ERROR",
		2: "UNKNOWN",
	}
	UnitsParamsResponce_Status_value = map[string]int32{
		"OK":      0,
		"ERROR":   1,
		"UNKNOWN": 2,
	}
)

func (x UnitsParamsResponce_Status) Enum() *UnitsParamsResponce_Status {
	p := new(UnitsParamsResponce_Status)
	*p = x
	return p
}

func (x UnitsParamsResponce_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UnitsParamsResponce_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_api_unit_unit_proto_enumTypes[0].Descriptor()
}

func (UnitsParamsResponce_Status) Type() protoreflect.EnumType {
	return &file_api_unit_unit_proto_enumTypes[0]
}

func (x UnitsParamsResponce_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UnitsParamsResponce_Status.Descriptor instead.
func (UnitsParamsResponce_Status) EnumDescriptor() ([]byte, []int) {
	return file_api_unit_unit_proto_rawDescGZIP(), []int{1, 0}
}

type UnitId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnitId uint64 `protobuf:"varint,1,opt,name=unit_id,json=unitId,proto3" json:"unit_id,omitempty"`
}

func (x *UnitId) Reset() {
	*x = UnitId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_unit_unit_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnitId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnitId) ProtoMessage() {}

func (x *UnitId) ProtoReflect() protoreflect.Message {
	mi := &file_api_unit_unit_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnitId.ProtoReflect.Descriptor instead.
func (*UnitId) Descriptor() ([]byte, []int) {
	return file_api_unit_unit_proto_rawDescGZIP(), []int{0}
}

func (x *UnitId) GetUnitId() uint64 {
	if x != nil {
		return x.UnitId
	}
	return 0
}

type UnitsParamsResponce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UnitName    string `protobuf:"bytes,2,opt,name=unit_name,json=unitName,proto3" json:"unit_name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *UnitsParamsResponce) Reset() {
	*x = UnitsParamsResponce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_unit_unit_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnitsParamsResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnitsParamsResponce) ProtoMessage() {}

func (x *UnitsParamsResponce) ProtoReflect() protoreflect.Message {
	mi := &file_api_unit_unit_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnitsParamsResponce.ProtoReflect.Descriptor instead.
func (*UnitsParamsResponce) Descriptor() ([]byte, []int) {
	return file_api_unit_unit_proto_rawDescGZIP(), []int{1}
}

func (x *UnitsParamsResponce) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UnitsParamsResponce) GetUnitName() string {
	if x != nil {
		return x.UnitName
	}
	return ""
}

func (x *UnitsParamsResponce) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_api_unit_unit_proto protoreflect.FileDescriptor

var file_api_unit_unit_proto_rawDesc = []byte{
	0x0a, 0x13, 0x61, 0x70, 0x69, 0x2f, 0x75, 0x6e, 0x69, 0x74, 0x2f, 0x75, 0x6e, 0x69, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x75, 0x69, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x1a, 0x1c,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d,
	0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x21, 0x0a, 0x06, 0x55, 0x6e, 0x69,
	0x74, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x6e, 0x69, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x6e, 0x69, 0x74, 0x49, 0x64, 0x22, 0x94, 0x01, 0x0a,
	0x13, 0x55, 0x6e, 0x69, 0x74, 0x73, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x6e, 0x69, 0x74, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x6e, 0x69, 0x74, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x28, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x06, 0x0a,
	0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01,
	0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x02, 0x4a, 0x04, 0x08,
	0x04, 0x10, 0x05, 0x32, 0x65, 0x0a, 0x0e, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x53,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x12, 0x53, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x55, 0x6e, 0x69, 0x74,
	0x42, 0x79, 0x49, 0x64, 0x12, 0x0f, 0x2e, 0x75, 0x69, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x55,
	0x6e, 0x69, 0x74, 0x49, 0x64, 0x1a, 0x1c, 0x2e, 0x75, 0x69, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e,
	0x55, 0x6e, 0x69, 0x74, 0x73, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x63, 0x65, 0x22, 0x15, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0f, 0x12, 0x0d, 0x2f, 0x76, 0x31,
	0x2f, 0x7b, 0x75, 0x6e, 0x69, 0x74, 0x5f, 0x69, 0x64, 0x7d, 0x42, 0x4b, 0x5a, 0x49, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x44, 0x69, 0x6d, 0x4b, 0x75, 0x73, 0x68,
	0x2f, 0x67, 0x6f, 0x5f, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2f, 0x74, 0x72, 0x65, 0x65,
	0x2f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x5f,
	0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x75, 0x6e, 0x69, 0x74, 0x3b,
	0x75, 0x6e, 0x69, 0x74, 0x5f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_unit_unit_proto_rawDescOnce sync.Once
	file_api_unit_unit_proto_rawDescData = file_api_unit_unit_proto_rawDesc
)

func file_api_unit_unit_proto_rawDescGZIP() []byte {
	file_api_unit_unit_proto_rawDescOnce.Do(func() {
		file_api_unit_unit_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_unit_unit_proto_rawDescData)
	})
	return file_api_unit_unit_proto_rawDescData
}

var file_api_unit_unit_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_unit_unit_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_unit_unit_proto_goTypes = []interface{}{
	(UnitsParamsResponce_Status)(0), // 0: uint.v1.UnitsParamsResponce.Status
	(*UnitId)(nil),                  // 1: uint.v1.UnitId
	(*UnitsParamsResponce)(nil),     // 2: uint.v1.UnitsParamsResponce
}
var file_api_unit_unit_proto_depIdxs = []int32{
	1, // 0: uint.v1.GreetingSample.GetUnitById:input_type -> uint.v1.UnitId
	2, // 1: uint.v1.GreetingSample.GetUnitById:output_type -> uint.v1.UnitsParamsResponce
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_unit_unit_proto_init() }
func file_api_unit_unit_proto_init() {
	if File_api_unit_unit_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_unit_unit_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnitId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_unit_unit_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnitsParamsResponce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_unit_unit_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_unit_unit_proto_goTypes,
		DependencyIndexes: file_api_unit_unit_proto_depIdxs,
		EnumInfos:         file_api_unit_unit_proto_enumTypes,
		MessageInfos:      file_api_unit_unit_proto_msgTypes,
	}.Build()
	File_api_unit_unit_proto = out.File
	file_api_unit_unit_proto_rawDesc = nil
	file_api_unit_unit_proto_goTypes = nil
	file_api_unit_unit_proto_depIdxs = nil
}
