// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package chatpb_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GreetingSampleClient is the client API for GreetingSample service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreetingSampleClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *ChatMessage, opts ...grpc.CallOption) (*ChatAnswer, error)
}

type greetingSampleClient struct {
	cc grpc.ClientConnInterface
}

func NewGreetingSampleClient(cc grpc.ClientConnInterface) GreetingSampleClient {
	return &greetingSampleClient{cc}
}

func (c *greetingSampleClient) SayHello(ctx context.Context, in *ChatMessage, opts ...grpc.CallOption) (*ChatAnswer, error) {
	out := new(ChatAnswer)
	err := c.cc.Invoke(ctx, "/chatpb.v1.GreetingSample/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreetingSampleServer is the server API for GreetingSample service.
// All implementations must embed UnimplementedGreetingSampleServer
// for forward compatibility
type GreetingSampleServer interface {
	// Sends a greeting
	SayHello(context.Context, *ChatMessage) (*ChatAnswer, error)
	mustEmbedUnimplementedGreetingSampleServer()
}

// UnimplementedGreetingSampleServer must be embedded to have forward compatible implementations.
type UnimplementedGreetingSampleServer struct {
}

func (UnimplementedGreetingSampleServer) SayHello(context.Context, *ChatMessage) (*ChatAnswer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedGreetingSampleServer) mustEmbedUnimplementedGreetingSampleServer() {}

// UnsafeGreetingSampleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreetingSampleServer will
// result in compilation errors.
type UnsafeGreetingSampleServer interface {
	mustEmbedUnimplementedGreetingSampleServer()
}

func RegisterGreetingSampleServer(s grpc.ServiceRegistrar, srv GreetingSampleServer) {
	s.RegisterService(&GreetingSample_ServiceDesc, srv)
}

func _GreetingSample_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreetingSampleServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatpb.v1.GreetingSample/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreetingSampleServer).SayHello(ctx, req.(*ChatMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// GreetingSample_ServiceDesc is the grpc.ServiceDesc for GreetingSample service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GreetingSample_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chatpb.v1.GreetingSample",
	HandlerType: (*GreetingSampleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _GreetingSample_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/chatpb/chat.proto",
}
